services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --bind-address=${DATABASE_IP_ADDRESS} --port=${DATABASE_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_HOST=${DATABASE_HOST}
      - MYSQL_PORT=${DATABASE_PORT}
      - MYSQL_IP_ADDRESS=${DATABASE_IP_ADDRESS}
    # ports:
    #   - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - app-network

  cache:
    container_name: cache
    image: redis:alpine
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ./.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network

  chatttty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatttty
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - cache
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cache:
    driver: local