services:
 chatttty:
   build: .
   container_name: chatttty
   ports:
     - "8000:8000"
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     MISTRAL_API_KEY: ${MISTRAL_API_KEY}
   env_file:
     - .env
   networks:
     - webnet
networks:
  webnet:
