services:
  - type: web
    plan: free
    name: chatttty
    runtime: python
    buildCommand: "bash ./build.sh"
    startCommand: "python -m gunicorn chatttty.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4