# Generated by Django 4.2.9 on 2025-03-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
