# Generated by Django 4.2.9 on 2025-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_promptmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
